# Generated by Django 5.1 on 2024-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicId', models.IntegerField()),
                ('title', models.CharField()),
                ('videoUrl', models.CharField(null=True)),
                ('accest', models.CharField(null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
