# Generated by Django 5.1 on 2024-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField()),
                ('durationIn', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('description', models.CharField()),
                ('free', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('image', models.CharField(null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
