# Generated by Django 5.1 on 2024-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
