# Generated by Django 5.1 on 2024-09-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
