# Generated by Django 5.1 on 2024-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.IntegerField()),
                ('title', models.CharField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
